books/urls.py
from django.urls import path

from books.views import BookListView, BookDetailView, SearchResultsListView

app_name = "books"

urlpatterns = [
    path("", BookListView.as_view(), name="book-list"),
    path("<uuid:pk>/", BookDetailView.as_view(), name="book-detail"),
    path("search/", SearchResultsListView.as_view(), name="search-results"),
]

bookstore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages.urls")),
    path("accounts/", include("allauth.urls")),
    path("books/", include("books.urls")),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

pages/urls.py
from django.urls import path

from pages.views import HomePageView, AboutPageView

app_name = "pages"

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

books/models.py
from uuid import uuid4

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


User = get_user_model()


class Book(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid4,
        editable=False
    )
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    cover = models.ImageField(upload_to="covers/", blank=True)

    class Meta:
        permissions = [
            ("special_status", "Can read all books"),
        ]

    def __str__(self):
        return self.title.title()

    def get_absolute_url(self):
        return reverse("books:book-detail", args=[str(self.id)])


class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="reviews")
    review = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.review

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("email", "username",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ("email", "username",)

books/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.views.generic import ListView, DetailView

from books.models import Book


class BookListView(LoginRequiredMixin, ListView):
    model = Book
    context_object_name = "book_list"
    template_name = "books/book_list.html"


class BookDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Book
    context_object_name = "book"
    template_name = "books/book_detail.html"
    login_url = "account_login"
    permission_required = "books.special_status"


class SearchResultsListView(ListView):
    model = Book
    context_object_name = "book_list"
    template_name = "books/search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        return Book.objects.filter(
            Q(title__icontains=query) | Q(title__icontains=query)
        )

pages/views.py
from django.views.generic import TemplateView, ListView

from books.models import Book

class HomePageView(TemplateView):
    template_name = "pages/home.html"

class AboutPageView(TemplateView):
    template_name = "pages/about.html"

templates/books/book_detail.html
{% extends "pages/_base.html" %}

{% block title %}{{ book.title }}{% endblock %}

{% block content %}
    <div class="book-detail">
        {% if book.cover %}
            <img src="{{ book.cover.url }}" alt="{{ book.title }}" class="bookcover">
        {% endif %}
        <h2>
            <a href="#">{{ book.title }}</a>
        </h2>
        <p>Author: {{ book.author }}</p>
        <p>Price: {{ book.price }}</p>
        <div>
            <h3>Review</h3>
            <ul>
                {% for review in book.reviews.all %}
                    <li>{{ review.review }} ({{ review.author }})</li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/books/book_list.html
{% extends "pages/_base.html" %}
{% block title %}Books{% endblock %}

{% block content %}
    {% for book in book_list %}
        <div>
            <h2><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></h2>
        </div>
    {% endfor %}
{% endblock %}

templates/books/search_results.html
{% extends "pages/_base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
    <h1>Search Results</h1>
    
    {% for book in book_list %}
        <div>
            <h3>
                <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
            </h3>
            <p>Author: {{ book.author }}</p>
            <p>Price: {{ book.price }}</p>
        </div>
    {% endfor %}
{% endblock %}

templates/pages/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Bookstore{% endblock %}</title>
    <!-- CSS -->
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
            crossorigin="anonymous"
    >
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<!-- Navbar -->
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
        <a href="#" class="navbar-brand">Bookstore</a>
        <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a href="{% url 'books:book-list' %}" class="nav-link">Books</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'pages:about' %}" class="nav-link">About</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'account_logout' %}" class="nav-link">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'account_login' %}" class="nav-link">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'account_signup' %}" class="nav-link">Sign Up</a>
                    </li>
                {% endif %}
            </ul>
            <!-- Search form -->
            <form class="d-flex" action="{% url 'books:search-results' %}" method="GET">
                <input type="search" class="form-control me-2" name="q" placeholder="Search" aria-label="Search">
                <button class="btn bt-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<!-- JavaScript -->
{% block javascript %}
    <script src="{% static 'js/base.js' %}"></script>
{% endblock %}
{% block JQuery %}
    <script
            src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
            integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
            crossorigin="anonymous"></script>
    <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/cjs/popper-base.min.js"
            integrity="sha512-o0ub2Xb68yocD2zlJF3T68IBMS6Tcci0ELYFMSZg22LpCZ9/zceGsjt9k7sH/HZbqCAzwewcXCzyOcjfIG21Ow=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>

templates/pages/about.html
{% extends "pages/_base.html" %}
{% block title %}About{% endblock %}

{% block content %}
    <h1>About Page</h1>
{% endblock %}

templates/pages/home.html
{% extends "pages/_base.html" %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>This is the Home page</h1>
    <img
            src="{% static 'images/djangoforprofessionals-scaled.webp' %}"
            alt="book cover"
            class="bookcover"
    >
    {% if user.is_authenticated %}
        <p>Hi {{ user.email }}!</p>
        <p>
            <a href="{% url 'account_logout' %}">Log Out</a>
        </p>
    {% else %}
        <p>You are not logged in</p>
        <p><a href="{% url 'account_login' %}">Log In</a></p>
        <p><a href="{% url 'account_signup' %}">Sign Up</a></p>
    {% endif %}
{% endblock %}